volumes:
  build:

services:
  cosmetology-server:
    image: dahakalab/cosmetology-backend:latest
    container_name: cosmetology-server
    restart: always
    ports:
      - 3000:3000

  cosmetology-admin-panel:
    depends_on:
      - cosmetology-server
    build:
      dockerfile: Dockerfile
    container_name: cosmetology-admin-panel
    environment:
      - REACT_APP_API_URL=127.0.0.1:3000
    volumes:
      - build:/app/build:ro

  cosmetology-web-server:
    depends_on:
      - cosmetology-admin-panel
    image: nginx:alpine
    container_name: cosmetology-client-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - build:/usr/share/nginx/app
